modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/vrglab/ExtremeRuby/issues"
license = "MIT"

[[mods]]
modId = "extreme_ruby"
version = "${version}"
displayName = "Extreme Ruby"
authors = "Vrglab"
description = '''
Remastered Version of the 1.12 mod Extreme Ruby
'''
logoFile = "logo.png"

[[dependencies.extreme_ruby]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extreme_ruby]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extreme_ruby]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.extreme_ruby]]
modId = "vrglabslib"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"
